package com.gaslab.microgas

import java.nio.ByteBuffer
import java.nio.ByteOrder
import java.util.zip.CRC32
import org.junit.Assert.*
import org.junit.Test

class PayloadProtocolTest {
    // Generated by integration/psdk/test_sender.c, compiled against the user's PSDK headers.
    private val fixture = "4d474153010100002a0000000700000040e201000000000000a0224419286167"
        .chunked(2).map { it.toInt(16).toByte() }.toByteArray()

    private fun packet(boot: Int = 42, sequence: Int = 7, co2: Float = 650.5f): ByteArray {
        val bytes = fixture.copyOf()
        val buffer = ByteBuffer.wrap(bytes).order(ByteOrder.LITTLE_ENDIAN)
        buffer.putInt(8, boot); buffer.putInt(12, sequence); buffer.putFloat(24, co2)
        buffer.putInt(28, CRC32().apply { update(bytes, 0, 28) }.value.toInt())
        return bytes
    }

    @Test fun decodesRealCPacket() {
        val sample = PayloadProtocol().decode(fixture, 999)!!
        assertEquals(650.5f, sample.co2Ppm, 0f)
        assertEquals(42L, sample.senderBoot)
        assertEquals(7L, sample.senderSequence)
        assertEquals(123456L, sample.acquiredUptimeMs)
        assertEquals(999L, sample.receivedAtMs)
        assertEquals("dji", sample.origin)
    }

    @Test fun rejectsCorruptionWrongLengthAndInvalidValues() {
        val decoder = PayloadProtocol()
        assertNull(decoder.decode(fixture.copyOf(12), 0))
        assertNull(decoder.decode(fixture.copyOf().apply { this[24] = 1 }, 0))
        assertNull(decoder.decode(packet(co2 = Float.NaN), 0))
        assertNull(decoder.decode(packet(co2 = -1f), 0))
        assertNotNull(decoder.decode(fixture, 0))
    }

    @Test fun skipsDuplicateAndOutOfOrderButAcceptsSameValueInNewSample() {
        val decoder = PayloadProtocol()
        assertNotNull(decoder.decode(packet(sequence = 7), 0))
        assertNull(decoder.decode(packet(sequence = 7), 1))
        assertNull(decoder.decode(packet(sequence = 6), 2))
        assertNotNull(decoder.decode(packet(sequence = 8), 3))
    }

    @Test fun acceptsSequenceWrapAndNewBootRejectsLatePreviousBoot() {
        val decoder = PayloadProtocol()
        assertNotNull(decoder.decode(packet(sequence = -1), 0))
        assertNotNull(decoder.decode(packet(sequence = 0), 1))
        assertNotNull(decoder.decode(packet(boot = 43, sequence = 0), 2))
        assertNull(decoder.decode(packet(boot = 42, sequence = 1), 3))
    }
}
